export const profile = {
  email: 'breezeyoung9470@gmail.com',
  github: 'https://github.com/breez3young',
  scholar: 'https://scholar.google.com/citations?user=2NxmmZwAAAAJ&hl=en',
  twitter: 'https://x.com/yang_zhang_',
};

export function publicationVenueLabel(paper) {
  if (/under review/i.test(paper.status) && !paper.links.Paper) return 'Manuscript';
  return /arxiv|preprint/i.test(`${paper.venue} ${paper.status}`)
    ? 'arXiv preprint'
    : paper.venue;
}

export const lastUpdated = 'October 2026';

export const publications = [
  {
    id: 'vjepa-policy',
    title: 'V-JEPA Policy: Building Effective World-Action Models on Predictive Visual Latents',
    authors: 'Yang Zhang, Jiangyuan Zhao, Chenyou Fan, Jiayu Hu, Xiu Yuan, Chenjia Bai, Xiu Li',
    venue: 'arXiv',
    year: '2026',
    preprintDate: '2026-09-29',
    status: 'Preprint',
    authorship: 'First author',
    note: "World-action models can learn to act by predicting visual latents rather than generating future pixels. V-JEPA Policy couples latent prediction with action generation and transfers predictive pretraining without action labels to downstream robot learning.",
    tags: ["World Models", "Robot Learning", "Representation Learning"],
    links: { Paper: 'https://arxiv.org/abs/2609.37250', Code: 'https://github.com/breez3young/VJEPA-Policy' },
  },
  {
    id: 'prts',
    title: 'PRTS: A Primitive Reasoning and Tasking System via Contrastive Representations',
    authors: 'Yang Zhang*†, Jiangyuan Zhao*, Chenyou Fan, Fangzheng Yan, Tian Li, Haitong Tang, Sen Fu, Xuan’er Wu, Qizhen Weng, Weinan Zhang, Xiu Li, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'CoRL',
    year: '2026',
    preprintDate: '2026-04-30',
    status: 'Spotlight',
    authorship: 'First author · project lead',
    citations: 1,
    note: "PRTS reframes VLA pretraining around language-goal reachability, learning from temporal structure as well as action imitation. Goal-conditioned contrastive RL turns offline trajectories into dense supervision for understanding task progress without reward annotations.",
    tags: ["Vision-Language-Action Models", "Reinforcement Learning", "Representation Learning"],
    links: { Paper: 'https://arxiv.org/abs/2604.27472', OpenReview: 'https://openreview.net/forum?id=QwpnI3BlwT', Code: 'https://github.com/TeleHuman/PRTS', Project: 'https://rhodes-team-prts.github.io/' },
  },
  {
    id: 'canvas',
    title: 'Wrist Matters: A Unified Novel View Synthesis Model for Robust Multi-View Robot Manipulation',
    authors: 'Chenyou Fan, Shuhang Zheng, Yang Zhang, Chenjia Bai',
    venue: 'CoRL',
    year: '2026',
    status: 'Under review',
    authorship: 'Co-author',
    note: "Wrist-view shifts create a robustness gap that head-view augmentation alone cannot resolve. CANVAS unifies head- and wrist-view synthesis as geometry-guided masked video inpainting, enabling camera augmentation from unpaired robot trajectories.",
    tags: ["Robot Learning", "Video Generation"],
    links: {},
  },
  {
    id: 'gr-bc',
    title: 'Graph-Reweighted Behavior Cloning with Human Interventions for Precise Robotic Manipulation',
    authors: 'Xiaoman Li, Zhiqiang Yang, Jiayu Hu, Jipeng Kong, Yang Zhang, Waylen Zhang, Fangzheng Yan, Chunhua Shen, Chenjia Bai',
    venue: 'CoRL',
    year: '2026',
    status: 'Accepted',
    authorship: 'Co-author',
    note: "Useful action chunks can occur inside failed rollouts, while successful demonstrations can contain regressions. GR-BC reweights chunks by reductions in graph-estimated steps to completion, extracting task-progress supervision from mixed-quality demonstrations and human interventions for VLA post-training.",
    tags: ["Vision-Language-Action Models", "Imitation Learning"],
    links: {},
  },
  {
    id: 'kinebench',
    title: 'KineBench: Benchmarking Embodied World Models via IDM-Free Kinematic Grounding',
    authors: 'Zeyu Liu*, Zhangzhe Zhu*, Yang Zhang*†, Chenyou Fan, Chenjia Bai, Xuelong Li',
    venue: 'ECCV',
    year: '2026',
    preprintDate: '2026-07-22',
    status: 'Accepted',
    authorship: 'Co-first author · project lead',
    citations: 1,
    note: "Learned inverse dynamics can confound world-model prediction errors with action-extraction errors. KineBench grounds generated videos in explicit robot kinematics for closed-loop execution, making physical feasibility and the source of failure easier to assess.",
    tags: ["World Models", "Robot Learning"],
    links: { Paper: 'https://arxiv.org/abs/2607.19876' },
  },
  {
    id: 'taco',
    title: 'Steering Vision-Language-Action Models as Anti-Exploration: A Test-Time Scaling Approach',
    authors: 'Siyuan Yang*, Yang Zhang*†, Haoran He, Ling Pan, Xiu Li, Chenjia Bai, Xuelong Li',
    venue: 'arXiv',
    year: '2025',
    preprintDate: '2025-12-02',
    status: 'Under review · #3 Hugging Face Daily Paper',
    authorship: 'Co-first author · project lead',
    citations: 14,
    note: "TACO treats unstable VLA sampling as a distribution-support problem. It uses learned pseudo-counts to select action chunks consistent with demonstration data, applying anti-exploration at inference without updating the VLA itself.",
    tags: ["Vision-Language-Action Models", "Robot Learning"],
    links: { Paper: 'https://arxiv.org/abs/2512.02834', Code: 'https://github.com/breez3young/TACO', Project: 'https://vla-anti-exploration.github.io/' },
  },
  {
    id: 'ate',
    title: 'Align-Then-stEer: Adapting the Vision-Language-Action Models through Unified Latent Guidance',
    authors: 'Yang Zhang*†, Chenwei Wang*, Ouyang Lu*, Yuan Zhao, Yunfei Ge, Zhenglong Sun, Xiu Li, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'ICLR',
    year: '2026',
    preprintDate: '2025-09-02',
    status: 'Accepted',
    authorship: 'First author · project lead',
    citations: 19,
    note: "Adapting a VLA to new robots and tasks requires resolving mismatched action distributions. Align-Then-stEer aligns actions in a shared latent space, then uses latent guidance during fine-tuning to steer the pretrained policy toward the target domain.",
    tags: ["Vision-Language-Action Models", "Transfer Learning"],
    links: { Paper: 'https://arxiv.org/abs/2509.02055', OpenReview: 'https://openreview.net/forum?id=T3i7Ifeatk', Code: 'https://github.com/TeleHuman/Align-Then-Steer', Project: 'https://align-then-steer.github.io/' },
  },
  {
    id: 'dp3r',
    title: 'Enhancing Dexterous Diffusion Policy with Predictive 3D Representations',
    authors: 'Siyuan Yang, Yang Zhang, Chenwei Wang, Ouyang Lu, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'Preprint',
    year: '2025',
    status: 'Under review',
    authorship: 'Co-author',
    note: "Short observation histories provide limited context for long-horizon dexterous actions. DP3R learns predictive 3D bottlenecks through masked trajectory modeling without action labels, then uses these future-oriented representations to condition diffusion policies trained on action-labeled demonstrations.",
    tags: ["Robot Learning", "Diffusion Models", "Representation Learning"],
    links: {},
  },
  {
    id: 'dima',
    title: 'Revisiting Multi-Agent World Modeling from a Diffusion-Inspired Perspective',
    authors: 'Yang Zhang, Xinran Li, Jianing Ye, Shuang Qiu, Delin Qu, Xiu Li, Chongjie Zhang, Chenjia Bai',
    venue: 'NeurIPS',
    year: '2025',
    preprintDate: '2025-05-27',
    status: 'Accepted',
    authorship: 'First author',
    citations: 15,
    note: "The complexity of multi-agent dynamics can be reduced by revealing agents' actions sequentially. DIMA connects this progressive reduction in state uncertainty to reverse diffusion, capturing agent interactions in a world model for policy learning in imagination.",
    tags: ["World Models", "Multi-Agent Systems", "Reinforcement Learning"],
    links: { Paper: 'https://arxiv.org/abs/2505.20922', Code: 'https://github.com/breez3young/DIMA' },
  },
  {
    id: 'dws',
    title: 'Pre-Trained Video Generative Models as World Simulators',
    authors: 'Haoran He, Yang Zhang, Liang Lin, Zhongwen Xu, Ling Pan',
    venue: 'AAAI',
    year: '2026',
    status: 'Published',
    authorship: 'Second author',
    citations: 48,
    note: "DWS adapts pretrained video generators into action-conditioned world simulators. Lightweight action conditioning and a motion-focused objective connect visual prediction with the effects of actions, supporting consistent state changes for interactive prediction and policy learning.",
    tags: ["World Models", "Video Generation", "Reinforcement Learning"],
    links: { Paper: 'https://arxiv.org/abs/2502.07825', Proceedings: 'https://ojs.aaai.org/index.php/AAAI/article/view/42465' },
  },
  {
    id: 'copo',
    title: 'Online Preference Alignment for Language Models via Count-based Exploration',
    authors: 'Chenjia Bai, Yang Zhang, Shuang Qiu, Qiaosheng Zhang, Kang Xu, Xuelong Li',
    venue: 'ICLR',
    year: '2025',
    status: 'Spotlight',
    authorship: 'Second author',
    citations: 53,
    note: "COPO addresses the limited coverage of preference data through active exploration during online alignment. A count-based bonus encourages the model to discover novel responses while balancing exploration with preference optimization.",
    tags: ["LLM Alignment", "Preference Learning"],
    links: { Paper: 'https://openreview.net/forum?id=cfKZ5VrhXt', Code: 'https://github.com/Baichenjia/COPO' },
  },
  {
    id: 'sodp',
    title: 'Task-Agnostic Pre-training and Task-Guided Fine-tuning for Versatile Diffusion Planner',
    authors: 'Chenyou Fan, Chenjia Bai, Zhao Shan, Haoran He, Yang Zhang, Zhen Wang',
    venue: 'ICML',
    year: '2025',
    status: 'Published',
    authorship: 'Fifth author',
    citations: 5,
    note: "SODP learns a reusable diffusion planner from diverse, suboptimal trajectories without task-specific rewards during pretraining. Reinforcement learning then adapts the pretrained planner to new downstream tasks using their associated reward signals.",
    tags: ["Diffusion Models", "Reinforcement Learning"],
    links: { Paper: 'https://proceedings.mlr.press/v267/fan25a.html' },
  },
  {
    id: 'oisa',
    title: 'Online Iterative Self-Alignment for Radiology Report Generation',
    authors: 'Ting Xiao, Lei Shi, Yang Zhang, HaoFeng Yang, Zhe Wang, Chenjia Bai',
    venue: 'ACL',
    year: '2025',
    status: 'Main conference',
    authorship: 'Third author',
    citations: 5,
    note: "OISA addresses limited preference-data coverage in radiology report generation. It iteratively generates candidate reports, evaluates them against multiple reporting objectives, and aligns the model with the resulting preference data to balance these objectives.",
    tags: ["Preference Learning", "Medical AI"],
    links: { Paper: 'https://aclanthology.org/2025.acl-long.1348/' },
  },
  {
    id: 'read',
    title: 'Towards Efficient LLM Grounding for Embodied Multi-Agent Collaboration',
    authors: 'Yang Zhang*†, Shixin Yang*, Chenjia Bai, Fei Wu, Xiu Li, Zhen Wang, Xuelong Li',
    venue: 'ACL Findings',
    year: '2025',
    preprintDate: '2024-05-23',
    status: 'Published',
    authorship: 'First author · project lead',
    citations: 99,
    note: "ReAd grounds LLM collaboration in each agent's contribution to team progress. It learns sequential advantage feedback from planned interactions and uses it to refine joint plans, bringing credit assignment into language-based coordination.",
    tags: ["Large Language Models", "Multi-Agent Systems"],
    links: { Paper: 'https://aclanthology.org/2025.findings-acl.84/', Project: 'https://read-llm.github.io/' },
  },
  {
    id: 'marie',
    title: 'Decentralized Transformers with Centralized Aggregation are Sample-Efficient Multi-Agent World Models',
    authors: 'Yang Zhang, Chenjia Bai, Bin Zhao, Junchi Yan, Xiu Li, Xuelong Li',
    venue: 'TMLR',
    year: '2025',
    preprintDate: '2024-06-22',
    status: 'Published',
    authorship: 'First author',
    citations: 21,
    note: "MARIE combines decentralized Transformer dynamics models with centralized aggregation to support learning policies in imagination. Local prediction helps the world model scale, while shared representations capture dependencies among agents for coordinated decision-making.",
    tags: ["World Models", "Multi-Agent Systems", "Reinforcement Learning"],
    links: { Paper: 'https://arxiv.org/abs/2406.15836', OpenReview: 'https://openreview.net/forum?id=xT8BEgXmVc', Code: 'https://github.com/breez3young/MARIE' },
  },
  {
    id: 'cross-domain',
    title: 'Contrastive Representation for Data Filtering in Cross-Domain Offline Reinforcement Learning',
    authors: 'Xiaoyu Wen, Chenjia Bai, Kang Xu, Xudong Yu, Yang Zhang, Xuelong Li, Zhen Wang',
    venue: 'ICML',
    year: '2024',
    status: 'Published',
    authorship: 'Fifth author',
    citations: 36,
    note: "IGDF learns contrastive representations to assess which source-domain transitions are useful for a target domain. Filtering source data by this compatibility helps offline reinforcement learning reuse experience despite differences in dynamics.",
    tags: ["Reinforcement Learning", "Transfer Learning", "Representation Learning"],
    links: { Paper: 'https://openreview.net/forum?id=rReWhol66R', Code: 'https://github.com/BattleWen/IGDF' },
  },
];
