export const profile = {
  email: 'breezeyoung9470@gmail.com',
  github: 'https://github.com/breez3young',
  scholar: 'https://scholar.google.com/citations?user=2NxmmZwAAAAJ&hl=en',
  twitter: 'https://x.com/yang_zhang_',
};

export function publicationVenueLabel(paper) {
  if (/under review/i.test(paper.status) && !paper.links.Paper) return 'Manuscript';
  return /arxiv|preprint/i.test(`${paper.venue} ${paper.status}`)
    ? 'arXiv preprint'
    : paper.venue;
}

export const lastUpdated = 'October 2026';

export const publications = [
  {
    id: 'smart',
    title: 'SMART: Zero-Shot Sim-to-Real Articulated Object Manipulation via Large-Scale Synthetic Pretraining',
    authors: 'Jicong Ao*†, Shuhan Jiang*, Yuling Zhong, Yanwen Liu, Yuhan Gao, Jiangyuan Zhao, Yang Zhang, Shiqiang Zhu, Chenjia Bai, Xuelong Li',
    venue: 'arXiv',
    year: '2026',
    preprintDate: '2026-10-06',
    status: 'Preprint',
    authorship: 'Co-author',
    note: "SMART addresses the scarcity of demonstrations for manipulating articulated objects by synthesizing trajectories that respect part semantics and joint constraints. Its articulation-aware simulation data supports VLA pretraining and task-specific policy learning for zero-shot sim-to-real transfer.",
    tags: ["VLA Pretraining", "Data Synthesis in Simulation", "Sim-to-Real Transfer"],
    links: { Paper: 'https://arxiv.org/abs/2610.07652', Project: 'https://teamillusion-smart.github.io/', Dataset: 'https://huggingface.co/datasets/TeleEmbodied/SMART-Data' },
  },
  {
    id: 'vjepa-policy',
    title: 'V-JEPA Policy: Building Effective World-Action Models on Predictive Visual Latents',
    authors: 'Yang Zhang, Jiangyuan Zhao, Chenyou Fan, Jiayu Hu, Xiu Yuan, Chenjia Bai, Xiu Li',
    venue: 'arXiv',
    year: '2026',
    preprintDate: '2026-09-29',
    status: 'Preprint',
    authorship: 'First author',
    note: "V-JEPA Policy builds world-action models on a frozen predictive visual encoder without inheriting a pretrained visual generator. It jointly learns future-latent prediction and action generation, transferring future-modeling knowledge from predictor pretraining on robot videos without action labels to downstream control.",
    tags: ["World-Action Models", "JEPA", "Predictive Representation Learning"],
    links: { Paper: 'https://arxiv.org/abs/2609.37250', Code: 'https://github.com/breez3young/VJEPA-Policy', Project: '/vjepa-policy/' },
  },
  {
    id: 'prts',
    title: 'PRTS: A Primitive Reasoning and Tasking System via Contrastive Representations',
    authors: 'Yang Zhang*†, Jiangyuan Zhao*, Chenyou Fan, Fangzheng Yan, Tian Li, Haitong Tang, Sen Fu, Xuan’er Wu, Qizhen Weng, Weinan Zhang, Xiu Li, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'CoRL',
    year: '2026',
    preprintDate: '2026-04-30',
    status: 'Spotlight',
    authorship: 'First author · project lead',
    citations: 1,
    note: "PRTS reframes VLA pretraining around language-goal reachability, learning from temporal structure as well as action imitation. Goal-conditioned contrastive RL turns offline trajectories into dense supervision for understanding task progress without reward annotations.",
    tags: ["VLA Pretraining", "Goal-Conditioned RL", "Contrastive Learning"],
    links: { Paper: 'https://arxiv.org/abs/2604.27472', OpenReview: 'https://openreview.net/forum?id=QwpnI3BlwT', Code: 'https://github.com/TeleHuman/PRTS', Project: 'https://rhodes-team-prts.github.io/' },
  },
  {
    id: 'canvas',
    title: 'Wrist Matters: A Unified Novel View Synthesis Model for Robust Multi-View Robot Manipulation',
    authors: 'Chenyou Fan, Shuhang Zheng, Yang Zhang, Chenjia Bai',
    venue: 'CoRL',
    year: '2026',
    status: 'Under review',
    authorship: 'Co-author',
    note: "Wrist-view shifts create a robustness gap that head-view augmentation alone cannot resolve. CANVAS unifies head- and wrist-view synthesis as geometry-guided masked video inpainting, enabling camera augmentation from unpaired robot trajectories.",
    tags: ["Novel View Synthesis", "Video Inpainting", "Data Augmentation"],
    links: {},
  },
  {
    id: 'gr-bc',
    title: 'Graph-Reweighted Behavior Cloning with Human Interventions for Precise Robotic Manipulation',
    authors: 'Xiaoman Li, Zhiqiang Yang, Jiayu Hu, Jipeng Kong, Yang Zhang, Waylen Zhang, Fangzheng Yan, Chunhua Shen, Chenjia Bai',
    venue: 'CoRL',
    year: '2026',
    status: 'Accepted',
    authorship: 'Co-author',
    note: "Useful action chunks can occur inside failed rollouts, while successful demonstrations can contain regressions. GR-BC reweights chunks by reductions in graph-estimated steps to completion, extracting task-progress supervision from mixed-quality demonstrations and human interventions for VLA post-training.",
    tags: ["VLA Post-Training", "Behavior Cloning", "Human-in-the-Loop Learning"],
    links: {},
  },
  {
    id: 'kinebench',
    title: 'KineBench: Benchmarking Embodied World Models via IDM-Free Kinematic Grounding',
    authors: 'Zeyu Liu*, Zhangzhe Zhu*, Yang Zhang*†, Chenyou Fan, Chenjia Bai, Xuelong Li',
    venue: 'ECCV',
    year: '2026',
    preprintDate: '2026-07-22',
    status: 'Accepted',
    authorship: 'Co-first author · project lead',
    citations: 1,
    note: "Learned inverse dynamics can confound world-model prediction errors with action-extraction errors. KineBench grounds generated videos in explicit robot kinematics for closed-loop execution, making physical feasibility and the source of failure easier to assess.",
    tags: ["Video World Models", "World Model Evaluation", "Robot Kinematics"],
    links: { Paper: 'https://arxiv.org/abs/2607.19876' },
  },
  {
    id: 'taco',
    title: 'Steering Vision-Language-Action Models as Anti-Exploration: A Test-Time Scaling Approach',
    authors: 'Siyuan Yang*, Yang Zhang*†, Haoran He, Ling Pan, Xiu Li, Chenjia Bai, Xuelong Li',
    venue: 'arXiv',
    year: '2025',
    preprintDate: '2025-12-02',
    status: 'Under review · #3 Hugging Face Daily Paper',
    authorship: 'Co-first author · project lead',
    citations: 14,
    note: "TACO addresses sampling-induced instability in VLAs through anti-exploration. It uses learned pseudo-counts to select well-supported action chunks from multiple candidates, improving action reliability through additional test-time sampling without updating the VLA.",
    tags: ["Vision-Language-Action Models", "Test-Time Scaling"],
    links: { Paper: 'https://arxiv.org/abs/2512.02834', Code: 'https://github.com/breez3young/TACO', Project: 'https://vla-anti-exploration.github.io/' },
  },
  {
    id: 'ate',
    title: 'Align-Then-stEer: Adapting the Vision-Language-Action Models through Unified Latent Guidance',
    authors: 'Yang Zhang*†, Chenwei Wang*, Ouyang Lu*, Yuan Zhao, Yunfei Ge, Zhenglong Sun, Xiu Li, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'ICLR',
    year: '2026',
    preprintDate: '2025-09-02',
    status: 'Accepted',
    authorship: 'First author · project lead',
    citations: 19,
    note: "Align-Then-stEer addresses action-distribution mismatch by aligning target-domain actions with modes of the pretrained latent action distribution. This alignment then guides fine-tuning through a unified latent formulation that supports both diffusion- and flow-based VLAs.",
    tags: ["VLA Post-Training", "Cross-Embodiment Adaptation", "Classifier Guidance"],
    links: { Paper: 'https://arxiv.org/abs/2509.02055', OpenReview: 'https://openreview.net/forum?id=T3i7Ifeatk', Code: 'https://github.com/TeleHuman/Align-Then-Steer', Project: 'https://align-then-steer.github.io/' },
  },
  {
    id: 'dp3r',
    title: 'Enhancing Dexterous Diffusion Policy with Predictive 3D Representations',
    authors: 'Siyuan Yang, Yang Zhang, Chenwei Wang, Ouyang Lu, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'Preprint',
    year: '2025',
    status: 'Under review',
    authorship: 'Co-author',
    note: "Short observation histories provide limited context for long-horizon dexterous actions. DP3R learns predictive 3D bottlenecks through masked trajectory modeling without action labels, then uses these future-oriented representations to condition diffusion policies trained on action-labeled demonstrations.",
    tags: ["Dexterous Manipulation", "Diffusion Policies", "Predictive Representation Learning"],
    links: {},
  },
  {
    id: 'dima',
    title: 'Revisiting Multi-Agent World Modeling from a Diffusion-Inspired Perspective',
    authors: 'Yang Zhang, Xinran Li, Jianing Ye, Shuang Qiu, Delin Qu, Xiu Li, Chongjie Zhang, Chenjia Bai',
    venue: 'NeurIPS',
    year: '2025',
    preprintDate: '2025-05-27',
    status: 'Accepted',
    authorship: 'First author',
    citations: 15,
    note: "The complexity of multi-agent dynamics can be reduced by revealing agents' actions sequentially. DIMA connects this progressive reduction in state uncertainty to reverse diffusion, capturing agent interactions in a world model for policy learning in imagination.",
    tags: ["Multi-Agent World Models", "Model-Based RL"],
    links: { Paper: 'https://arxiv.org/abs/2505.20922', Code: 'https://github.com/breez3young/DIMA' },
  },
  {
    id: 'dws',
    title: 'Pre-Trained Video Generative Models as World Simulators',
    authors: 'Haoran He, Yang Zhang, Liang Lin, Zhongwen Xu, Ling Pan',
    venue: 'AAAI',
    year: '2026',
    status: 'Published',
    authorship: 'Second author',
    citations: 48,
    note: "Pretrained video generators lack the frame-level action control needed for interactive simulation. DWS adds architecture-agnostic action conditioning and motion-focused training to capture action-induced changes, then prioritizes informative imagined experience for policy learning.",
    tags: ["Video World Models", "Model-Based RL"],
    links: { Paper: 'https://arxiv.org/abs/2502.07825', Proceedings: 'https://ojs.aaai.org/index.php/AAAI/article/view/42465' },
  },
  {
    id: 'copo',
    title: 'Online Preference Alignment for Language Models via Count-based Exploration',
    authors: 'Chenjia Bai, Yang Zhang, Shuang Qiu, Qiaosheng Zhang, Kang Xu, Xuelong Li',
    venue: 'ICLR',
    year: '2025',
    status: 'Spotlight',
    authorship: 'Second author',
    citations: 53,
    note: "COPO makes exploration an explicit part of online preference alignment. Motivated by optimistic RLHF, it augments direct preference optimization with a learned pseudo-count bonus, encouraging LLMs to explore beyond existing preference-data coverage while learning from preference feedback.",
    tags: ["Online Preference Optimization", "Count-Based Exploration"],
    links: { Paper: 'https://openreview.net/forum?id=cfKZ5VrhXt', Code: 'https://github.com/Baichenjia/COPO' },
  },
  {
    id: 'sodp',
    title: 'Task-Agnostic Pre-training and Task-Guided Fine-tuning for Versatile Diffusion Planner',
    authors: 'Chenyou Fan, Chenjia Bai, Zhao Shan, Haoran He, Yang Zhang, Zhen Wang',
    venue: 'ICML',
    year: '2025',
    status: 'Published',
    authorship: 'Fifth author',
    citations: 5,
    note: "SODP learns a reusable diffusion planner from diverse, suboptimal trajectories without task-specific rewards during pretraining. Reinforcement learning then adapts the pretrained planner to new downstream tasks using their associated reward signals.",
    tags: ["Diffusion Policies", "Multi-Task Learning"],
    links: { Paper: 'https://proceedings.mlr.press/v267/fan25a.html' },
  },
  {
    id: 'oisa',
    title: 'Online Iterative Self-Alignment for Radiology Report Generation',
    authors: 'Ting Xiao, Lei Shi, Yang Zhang, HaoFeng Yang, Zhe Wang, Chenjia Bai',
    venue: 'ACL',
    year: '2025',
    status: 'Main conference',
    authorship: 'Third author',
    citations: 5,
    note: "OISA enables a radiology report generator to improve using its own continually refreshed preference data. It conditions report generation on different objectives, evaluates the resulting reports, and iterates multi-objective preference optimization to balance fluency and clinical accuracy.",
    tags: ["Radiology Report Generation", "Multi-Objective Optimization", "Online Preference Optimization"],
    links: { Paper: 'https://aclanthology.org/2025.acl-long.1348/' },
  },
  {
    id: 'read',
    title: 'Towards Efficient LLM Grounding for Embodied Multi-Agent Collaboration',
    authors: 'Yang Zhang*†, Shixin Yang*, Chenjia Bai, Fei Wu, Xiu Li, Zhen Wang, Xuelong Li',
    venue: 'ACL Findings',
    year: '2025',
    preprintDate: '2024-05-23',
    status: 'Published',
    authorship: 'First author · project lead',
    citations: 99,
    note: "ReAd turns multi-agent credit assignment into feedback for LLM planning. Learned advantage functions evaluate how actions contribute to team objectives, guiding joint or sequential plan refinement while reducing reliance on repeated environment interactions and LLM queries.",
    tags: ["LLM Planning", "Multi-Agent Coordination", "Credit Assignment"],
    links: { Paper: 'https://aclanthology.org/2025.findings-acl.84/', Project: 'https://read-llm.github.io/' },
  },
  {
    id: 'marie',
    title: 'Decentralized Transformers with Centralized Aggregation are Sample-Efficient Multi-Agent World Models',
    authors: 'Yang Zhang, Chenjia Bai, Bin Zhao, Junchi Yan, Xiu Li, Xuelong Li',
    venue: 'TMLR',
    year: '2025',
    preprintDate: '2024-06-22',
    status: 'Published',
    authorship: 'First author',
    citations: 21,
    note: "MARIE addresses the trade-off between scalability and cross-agent dependence in multi-agent world modeling. Decentralized autoregressive Transformers predict local dynamics using centrally aggregated information, producing consistent imagined trajectories for sample-efficient policy learning.",
    tags: ["Multi-Agent World Models", "Model-Based RL"],
    links: { Paper: 'https://arxiv.org/abs/2406.15836', OpenReview: 'https://openreview.net/forum?id=xT8BEgXmVc', Code: 'https://github.com/breez3young/MARIE' },
  },
  {
    id: 'cross-domain',
    title: 'Contrastive Representation for Data Filtering in Cross-Domain Offline Reinforcement Learning',
    authors: 'Xiaoyu Wen, Chenjia Bai, Kang Xu, Xudong Yu, Yang Zhang, Xuelong Li, Zhen Wang',
    venue: 'ICML',
    year: '2024',
    status: 'Published',
    authorship: 'Fifth author',
    citations: 36,
    note: "Reusing source-domain data can harm offline reinforcement learning when transition dynamics differ. IGDF uses contrastive learning to estimate a mutual-information gap between domains, filtering source transitions to supplement scarce target data with dynamically compatible experience.",
    tags: ["Offline RL", "Domain Adaptation", "Contrastive Learning"],
    links: { Paper: 'https://openreview.net/forum?id=rReWhol66R', Code: 'https://github.com/BattleWen/IGDF' },
  },
];
