export const profile = {
  email: 'breezeyoung9470@gmail.com',
  github: 'https://github.com/breez3young',
  scholar: 'https://scholar.google.com/citations?user=2NxmmZwAAAAJ&hl=en',
  twitter: 'https://x.com/yang_zhang_',
};

export function publicationVenueLabel(paper) {
  return /arxiv|preprint/i.test(`${paper.venue} ${paper.status}`)
    ? 'arXiv preprint'
    : paper.venue;
}

export const publications = [
  {
    id: 'prts',
    title: 'PRTS: A Primitive Reasoning and Tasking System via Contrastive Representations',
    authors: 'Yang Zhang*†, Jiangyuan Zhao*, Chenyou Fan, Fangzheng Yan, Tian Li, Haitong Tang, Sen Fu, Xuan’er Wu, Qizhen Weng, Weinan Zhang, Xiu Li, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'SemRob & WCBM Workshops',
    year: '2026',
    preprintDate: '2026-04-30',
    status: 'Accepted to SemRob and WCBM',
    authorship: 'First author · project lead',
    citations: 1,
    note: 'Reframes policy pre-training as goal-conditioned reinforcement learning and learns temporal goal reachability from reward-free trajectories.',
    links: { Paper: 'https://arxiv.org/abs/2604.27472', Code: 'https://github.com/TeleHuman/PRTS', Project: 'https://rhodes-team-prts.github.io/' },
  },
  {
    id: 'canvas',
    title: 'Wrist Matters: A Unified Novel View Synthesis Model for Robust Multi-View Robot Manipulation',
    authors: 'Chenyou Fan, Shuhang Zheng, Yang Zhang, Chenjia Bai',
    venue: 'CoRL',
    year: '2026',
    status: 'Under review',
    authorship: 'Co-author',
    note: 'A camera-agnostic novel-view synthesis model for robust multi-view manipulation under head- and wrist-camera perturbations.',
    links: {},
  },
  {
    id: 'gr-bc',
    title: 'Graph-Reweighted Behavior Cloning with Human Interventions for Precise Robotic Manipulation',
    authors: 'Xiaoman Li, Zhiqiang Yang, Jiayu Hu, Jipeng Kong, Yang Zhang, Waylen Zhang, Fangzheng Yan, Chunhua Shen, Chenjia Bai',
    venue: 'CoRL',
    year: '2026',
    status: 'Under review',
    authorship: 'Co-author',
    note: 'Uses a goal-reachability graph to reweight action chunks from mixed-quality intervention data without a reward model or progress labels.',
    links: {},
  },
  {
    id: 'kinebench',
    title: 'KineBench: Benchmarking Embodied World Models via IDM-Free Kinematic Grounding',
    authors: 'Zeyu Liu*, Zhangzhe Zhu*, Yang Zhang*†, Chenyou Fan, Chenjia Bai, Xuelong Li',
    venue: 'ECCV',
    year: '2026',
    preprintDate: '2026-07-22',
    status: 'Accepted',
    authorship: 'Co-first author · project lead',
    citations: 1,
    note: 'An IDM-free, closed-loop benchmark for evaluating embodied world models through kinematic grounding.',
    links: { Paper: 'https://arxiv.org/abs/2607.19876' },
  },
  {
    id: 'taco',
    title: 'Steering Vision-Language-Action Models as Anti-Exploration: A Test-Time Scaling Approach',
    authors: 'Siyuan Yang*, Yang Zhang*†, Haoran He, Ling Pan, Xiu Li, Chenjia Bai, Xuelong Li',
    venue: 'arXiv',
    year: '2025',
    preprintDate: '2025-12-02',
    status: 'Under review · #3 Hugging Face Daily Paper',
    authorship: 'Co-first author · project lead',
    citations: 14,
    note: 'Improves decision-making at test time through training-free anti-exploration over candidate action chunks.',
    links: { Paper: 'https://arxiv.org/abs/2512.02834', Code: 'https://github.com/breez3young/TACO', Project: 'https://vla-anti-exploration.github.io/' },
  },
  {
    id: 'ate',
    title: 'Align-Then-stEer: Adapting the Vision-Language-Action Models through Unified Latent Guidance',
    authors: 'Yang Zhang*†, Chenwei Wang*, Ouyang Lu*, Yuan Zhao, Yunfei Ge, Zhenglong Sun, Xiu Li, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'ICLR',
    year: '2026',
    preprintDate: '2025-09-02',
    status: 'Accepted',
    authorship: 'First author · project lead',
    citations: 19,
    note: 'A unified latent alignment and guidance framework for efficiently adapting pre-trained VLA models to new robots.',
    links: { Paper: 'https://arxiv.org/abs/2509.02055', OpenReview: 'https://openreview.net/forum?id=T3i7Ifeatk', Code: 'https://github.com/TeleHuman/Align-Then-Steer', Project: 'https://align-then-steer.github.io/' },
  },
  {
    id: 'dp3r',
    title: 'Enhancing Dexterous Diffusion Policy with Predictive 3D Representations',
    authors: 'Siyuan Yang, Yang Zhang, Chenwei Wang, Ouyang Lu, Chi Zhang, Chenjia Bai, Xuelong Li',
    venue: 'Preprint',
    year: '2025',
    status: 'Under review',
    authorship: 'Co-author',
    note: 'Uses predictive 3D representations to improve long-horizon action generation for dexterous manipulation.',
    links: {},
  },
  {
    id: 'dima',
    title: 'Revisiting Multi-Agent World Modeling from a Diffusion-Inspired Perspective',
    authors: 'Yang Zhang, Xinran Li, Jianing Ye, Shuang Qiu, Delin Qu, Xiu Li, Chongjie Zhang, Chenjia Bai',
    venue: 'NeurIPS',
    year: '2025',
    preprintDate: '2025-05-27',
    status: 'Accepted',
    authorship: 'First author',
    citations: 15,
    note: 'DIMA is a sample-efficient, diffusion-inspired multi-agent world model.',
    links: { Paper: 'https://arxiv.org/abs/2505.20922', Code: 'https://github.com/breez3young/DIMA' },
  },
  {
    id: 'dws',
    title: 'Pre-Trained Video Generative Models as World Simulators',
    authors: 'Haoran He, Yang Zhang, Liang Lin, Zhongwen Xu, Ling Pan',
    venue: 'AAAI',
    year: '2026',
    status: 'Published',
    authorship: 'Second author',
    citations: 48,
    note: 'Turns pre-trained video generators into controllable simulators and uses their imagined trajectories for downstream reinforcement learning.',
    links: { Paper: 'https://arxiv.org/abs/2502.07825', Proceedings: 'https://ojs.aaai.org/index.php/AAAI/article/view/42465' },
  },
  {
    id: 'copo',
    title: 'Online Preference Alignment for Language Models via Count-based Exploration',
    authors: 'Chenjia Bai, Yang Zhang, Shuang Qiu, Qiaosheng Zhang, Kang Xu, Xuelong Li',
    venue: 'ICLR',
    year: '2025',
    status: 'Spotlight',
    authorship: 'Second author',
    citations: 53,
    note: 'Introduces count-based online preference optimization to improve exploration and data coverage during online alignment.',
    links: { Paper: 'https://openreview.net/forum?id=cfKZ5VrhXt', Code: 'https://github.com/Baichenjia/COPO' },
  },
  {
    id: 'sodp',
    title: 'Task-Agnostic Pre-training and Task-Guided Fine-tuning for Versatile Diffusion Planner',
    authors: 'Chenyou Fan, Chenjia Bai, Zhao Shan, Haoran He, Yang Zhang, Zhen Wang',
    venue: 'ICML',
    year: '2025',
    status: 'Published',
    authorship: 'Fifth author',
    citations: 5,
    note: 'Pre-trains a general diffusion planner on task-agnostic suboptimal trajectories and adapts it with reward-guided fine-tuning.',
    links: { Paper: 'https://proceedings.mlr.press/v267/fan25a.html' },
  },
  {
    id: 'oisa',
    title: 'Online Iterative Self-Alignment for Radiology Report Generation',
    authors: 'Ting Xiao, Lei Shi, Yang Zhang, HaoFeng Yang, Zhe Wang, Chenjia Bai',
    venue: 'ACL',
    year: '2025',
    status: 'Main conference',
    authorship: 'Third author',
    citations: 5,
    note: 'Iteratively generates preference data and aligns radiology reports with multiple clinical objectives.',
    links: { Paper: 'https://aclanthology.org/2025.acl-long.1348/' },
  },
  {
    id: 'read',
    title: 'Towards Efficient LLM Grounding for Embodied Multi-Agent Collaboration',
    authors: 'Yang Zhang*†, Shixin Yang*, Chenjia Bai, Fei Wu, Xiu Li, Zhen Wang, Xuelong Li',
    venue: 'ACL Findings',
    year: '2025',
    preprintDate: '2024-05-23',
    status: 'Published',
    authorship: 'First author · project lead',
    citations: 99,
    note: 'Introduces Reinforced Advantage feedback to ground language-model planning in efficient embodied multi-agent collaboration.',
    links: { Paper: 'https://aclanthology.org/2025.findings-acl.84/', Project: 'https://read-llm.github.io/' },
  },
  {
    id: 'marie',
    title: 'Decentralized Transformers with Centralized Aggregation are Sample-Efficient Multi-Agent World Models',
    authors: 'Yang Zhang, Chenjia Bai, Bin Zhao, Junchi Yan, Xiu Li, Xuelong Li',
    venue: 'TMLR',
    year: '2025',
    preprintDate: '2024-06-22',
    status: 'Published',
    authorship: 'First author',
    citations: 21,
    note: 'A Transformer-based multi-agent world model for sample-efficient policy learning in imagination.',
    links: { Paper: 'https://arxiv.org/abs/2406.15836', OpenReview: 'https://openreview.net/forum?id=xT8BEgXmVc', Code: 'https://github.com/breez3young/MARIE' },
  },
  {
    id: 'cross-domain',
    title: 'Contrastive Representation for Data Filtering in Cross-Domain Offline Reinforcement Learning',
    authors: 'Xiaoyu Wen, Chenjia Bai, Kang Xu, Xudong Yu, Yang Zhang, Xuelong Li, Zhen Wang',
    venue: 'ICML',
    year: '2024',
    status: 'Published',
    authorship: 'Fifth author',
    citations: 36,
    note: 'Uses contrastive representations to measure dynamics gaps and filter data for cross-domain offline reinforcement learning.',
    links: { Paper: 'https://openreview.net/forum?id=rReWhol66R', Code: 'https://github.com/BattleWen/IGDF' },
  },
];
